CREATE TABLE IF NOT EXISTS job (
    id UUID NOT NULL PRIMARY KEY,
    job VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS person (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS family (
    id UUID NOT NULL PRIMARY KEY,
    size SMALLINT NOT NULL
);